[book]
title = "CPP"
authors = ["Dev Namdev"]
language = "en"
src = "src"

[build]
build-dir = "../../docs/cpp"


[output.html]
git-repository-url = "https://github.com/devnamdev2003/devdocs"
edit-url-template = "https://github.com/devnamdev2003/devdocs/edit/main/md-code/cpp/{path}"
