[book]
authors = ["Dev Namdev"]
language = "en"
src = "src"

[build]
build-dir = "../../docs/mssql"



[output.html]
git-repository-url = "https://github.com/devnamdev2003/devdocs"
edit-url-template = "https://github.com/devnamdev2003/devdocs/edit/main/md-code/mssql/{path}"
