[book]
description = "Step-by-step AWS labs and hands-on exercises for real-world cloud practice."
authors = ["Dev Namdev"]
language = "en"
src = "src"

[build]
build-dir = "../../docs/aws-hands-on"


[output.html]
git-repository-url = "https://github.com/devnamdev2003/devdocs"
edit-url-template = "https://github.com/devnamdev2003/devdocs/edit/main/md-code/aws-hands-on/{path}"
