[book]
description = "Concise and practical Linux notes covering core commands, file systems, permissions, processes, networking, and system administration."
authors = ["Dev Namdev"]
language = "en"
src = "src"

[build]
build-dir = "../../docs/linux"


[output.html]
git-repository-url = "https://github.com/devnamdev2003/devdocs"
edit-url-template = "https://github.com/devnamdev2003/devdocs/edit/main/md-code/linux/{path}"
