[book]
description = "Practical JavaScript notes with core concepts, examples, and browser usage."
authors = ["Dev Namdev"]
language = "en"
src = "src"

[build]
build-dir = "../../docs/javascript"


[output.html]
git-repository-url = "https://github.com/devnamdev2003/devdocs"
edit-url-template = "https://github.com/devnamdev2003/devdocs/edit/main/md-code/javascript/{path}"
